export const CHANGE_WINDOW_HEIGHT = 'CHANGE_WINDOW_HEIGHT';
export const CACHE_HEAD_HEIGHT = 'CACHE_HEAD_HEIGHT';
export const CACHE_FOOT_HEIGHT = 'CACHE_FOOT_HEIGHT';
export const CHANGE_DIRECTORY_DATA = 'CHANGE_DIRECTORY_DATA';